name: Rokku feature
on:
  push:
    branches-ignore:
      - master

env:
  DOCKER_REPO: wbaa/rokku

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
#  it-tests takes too long so for feature we skip this

  feature-publish-image:
    needs: tests
    runs-on: ubuntu-latest
    name: publish feature
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
      - name: Build and publish docker image
        run: |
          # Login to docker
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          # Build docker image
          echo "Build image $DOCKER_REPO:${GITHUB_REF##*/}";
          ROKKU_VERSION=${GITHUB_REF##*/} sbt clean docker:publish;
