name: Rokku feature
on:
  push:
    branches-ignore:
      - master

env:
  DOCKER_REPO: wbaa/rokku

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
#  it-tests takes too long so for feature we skip this

  feature-publish-image:
    needs: tests
    runs-on: ubuntu-latest
    name: publish feature
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup Scala
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Build and publish docker image
        run: |
          # Login to docker
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          # Build docker image
          echo "Build image $DOCKER_REPO:${GITHUB_REF##*/}";
          ROKKU_VERSION=${GITHUB_REF##*/} sbt clean docker:publish;
