name: It tests
on: [workflow_call]

jobs:
  it-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Add s3.localhost to /etc/hosts to be able to run it test on ceph"
        run: echo "127.0.0.1 s3.localhost" | sudo tee -a /etc/hosts
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: sbt
      - name: "Starting dependent containers for testing"
        run: docker-compose up -d keycloak ceph postgres-server mariadb ranger-admin rokku-sts
      - name: "Install aws cli"
        run: pip install --user awscli==1.18.222
      - name: "Compile the project while containers are starting up"
        run: sbt clean compile
      - name: "Wait for containers to be up and running"
        run: bash waitForContainerSetup.sh
      - name: "setup s3"
        run: bash setupS3Env.sh
      - name: "Running it tests"
        run: sbt clean coverage it:test coverageReport
