name: Rokku master branch build

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: wbaa/rokku

jobs:
  m-tests:
    uses: ./.github/workflows/tests.yml

  m-it-tests:
    uses: ./.github/workflows/it-tests.yml

  tag:
    runs-on: ubuntu-latest
    needs: [m-tests, m-it-tests]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true
          VERBOSE: true
          DEFAULT_BUMP: patch

  publish-image-latest:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup Scala
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y
      - name: Build and publish docker image
        run: |
          # Login to docker
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          # Build docker image
          ROKKU_VERSION=$(git describe --tags --abbrev=0) sbt clean docker:publish;
          echo "Built image $DOCKER_REPO:$(git describe --tags --abbrev=0)";
          # Add latest tag
          docker tag $DOCKER_REPO:$(git describe --tags --abbrev=0) $DOCKER_REPO:latest;
          docker push $DOCKER_REPO:$(git describe --tags --abbrev=0)
          docker push $DOCKER_REPO:latest

